### ISSUE TITLE
[minor] Interface naming

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#1]
`item` is wrong, the name should be less generic and refer to the actual object being interfaced. Also, the `Interface` part of the name is already implicit, so it doesn't needs to be added.

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L9

**Comment by Asturiana88** [comment]
Resolved in **Issue 1 Interface naming 5e9408e**
