### ISSUE TITLE
 [minor] File structure

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#10]
Make a folder for each component, and put inside the component and it's stylesheet on different files.

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L229

**Comment by Asturiana88** [comment]
Modified in **Issue 10 File structure 7b2463a**
