### ISSUE TITLE
[minor] Variable name typo

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#3]
This variable should either be called `isModalVisible` or `modalVisibility`, for understanding porpuses

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L61

**Comment by Asturiana88** [comment]
Resolved in **Issue 3 Variable name typo 0131fd8**
