### ISSUE TITLE
[minor] Implicit return

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#4]
Well, you know this one haha

EDIT: Check other implicit returns around your repo, you gotta find 'em all.

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L78

**Comment by Asturiana88** [comment]
Resolver in **Issue 4 Implicit return bd2e5a3**
