### ISSUE TITLE
[CRITICAL] Non-boolean value

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#6]
Converting a value to boolean before using it into an `and` operator should always be imperative. You can use double negation if needed. Remember that empty objects and arrays always return `true`

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L193

**Comment by Asturiana88** [comment]
Resolved in **Issue 6-9 Non-boolean value 180f920**
