### ISSUE TITLE
[minor] Query name

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#7]
The `data` part of the name should be less generic. State what kind of data you're retrieving from this query.

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L63

**Comment by Asturiana88** [comment]
Resolved in **Issue 7 Query name 84b462b**
