### ISSUE TITLE
[question] Key extraction

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactNativeChallenge#8]
The `id` should be sufficient in most cases. If not, use a better entity filter, such as the type, to handle similar id's between different data models

https://github.com/Asturiana88/ReactNativeChallenge/blob/1d6b98c53dc5cb76d6626b0131f0f90316ed4c57/components/ContentHandler.tsx#L199

**Comment by Asturiana88** [comment]
Modified in **Issue 8 Key extraction c584691**
